# Generated by Django 4.0.4 on 2022-06-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_value_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='value',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='value',
            name='tag',
        ),
        migrations.AddField(
            model_name='candidate',
            name='tags',
            field=models.ManyToManyField(to='candidates.tag'),
        ),
        migrations.AddField(
            model_name='tag',
            name='values',
            field=models.ManyToManyField(to='candidates.value'),
        ),
    ]
